import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { Pokemon } from '../types/Pokemon'
import Header from '../components/header/Header'
import Input from '../components/input-bar/Input'
import CardContent from '../components/card-content/CardContent'

interface PokemonList {
  pokemonList: Pokemon[]
}

function Home({ pokemonList }: PokemonList) {

  const [pokemonSearch, setpokemonSearch] = useState("")

  function handleTextSended( pokemon: String ) {
    setpokemonSearch( pokemon.toLowerCase() )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className={styles.main}>
        <div className={styles.input_row}>
          <Input sendText={ handleTextSended }></Input>
        </div>
        { pokemonSearch !== "" ?
          (
            <div className={styles.grid_search}>
              {
                pokemonList.filter( p => p.name === pokemonSearch ).map((pokemon: Pokemon) => (
                  <div key={pokemon.id} className={styles.card}>
                    <CardContent pokemon={ pokemon }></CardContent>
                  </div>
                ))
              }
            </div>
          )
          :
          (
            <div className={styles.grid}>
            {
              pokemonList.map((pokemon: Pokemon) => (
                <div key={pokemon.id} className={styles.card}>
                  <CardContent pokemon={ pokemon }></CardContent>
                </div>
              ))
            }
            </div>
          )
        }
      </main>
    </div>
  )
}

export async function getStaticProps() {
  let pokemonList: Pokemon[] = []

  for(let id = 1; id <= 898; id++) { //898 total in pokeAPI
    const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`)
    const pokemon = await res.json()
    pokemonList.push(pokemon)
  }

  return {
    props: {
      pokemonList
    }
  }
}

export default Home